<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param $ticket
     * @return array
     */
    public function getComment($ticket) {
        return $this->createQueryBuilder('c')
            ->select('c.comment as comment', 'u.id as user_id' ,'up.firstname', 'up.lastname', 'c.creationDate', 'c.updateDate', 'c.id')
            ->join('c.ticket', 't')
            ->join('c.user', 'u')
            ->join('u.userProfile','up')
            ->where('c.ticket = :ticket')
            ->orderBy('c.creationDate', 'DESC')
            ->setParameter('ticket', $ticket)
            ->getQuery()
            ->getResult();
    }
}
