<?php

namespace AppBundle\Entity;

/**
 * TechnicalEvolutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicalEvolutionRepository extends \Doctrine\ORM\EntityRepository
{
}
