<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    /**
     * @param int $page
     * @param int $maxTickets
     * @return Paginator
     */
    public function getList($page = 1, $maxTickets = 10)
    {
        $q = $this->createQueryBuilder('t')
            ->orderBy('t.emergency','ASC')
            ->addOrderBy('t.id', 'DESC')
            ->setFirstResult(($page - 1) * $maxTickets)
            ->setMaxResults($maxTickets);
        //exit(dump($q->getQuery()->getResult()));

        return new Paginator($q, $fetchJoinCollection = false);
    }

    /**
     * @return mixed
     */
    public function countTicketTotal()
    {
        $q = $this->createQueryBuilder('t')
            ->select('COUNT(t)')
            ->getQuery()->getSingleScalarResult()
        ;
        return $q;
    }
}
