<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileRepository extends EntityRepository
{
    const MAX_RESULT = 10;

    public function getRowByPage($page, $filter)
    {
        $alias = "up";
        $query = $this->createQueryBuilder($alias)
            ->select($alias)
            ->setFirstResult(($page - 1) * self::MAX_RESULT)
            ->setMaxResults(self::MAX_RESULT);
        if (!is_null($filter)) {
            foreach ($filter as $field => $value) {
                if ($value !== "") {
                    if (strpos($field, "_") !== 0) {
                        $search = "$alias.$field like '%$value%'";
                        $query->andWhere($search);
                    }
                }
            }
        }
        return $query->getQuery();
    }
}