app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /


#someaction:
 #   pattern:  /someaction
  #  defaults: { _controller: AppBundle:Index:someAction }
   # options:  { mobile: redirect, tablet: no_redirect, full: redirect_without_path }