# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # Specific dictionary action (verification)
    app.dictionary_verification:
        class: AppBundle\Service\DictionaryVerification
        arguments: ["@doctrine.orm.entity_manager"]

    # Mailing service
    app.email.sending:
        class: AppBundle\Service\MaillerService
        arguments: ['@swiftmailer.mailer', '%mailer_sender_address%']

    # Service to get user by roles
    app.getter_user_admin:
        class: AppBundle\Service\GetterUserAdmin
        arguments: ['@doctrine.orm.entity_manager']

    # Navigator Factory
    app.navigator.factory:
        class: AppBundle\Service\NavigatorFactory
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"

    # Navigator Service (Search/Filter/Pagination)
    app.navigator:
        class: AppBundle\Service\Navigator
        factory: "app.navigator.factory:get"

    # Read Docfiles (download)
    app.read_docfiles:
        class: AppBundle\Service\ReadDocfiles
        arguments: ['@security.authorization_checker', '@security.token_storage', '%docfiles_directory%']