# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.sql.search_params_getter:
        class: AppBundle\Service\SqlWhereParamsSetter
        arguments: []

    app.dictionary_verification:
        class: AppBundle\Service\DictionaryVerification
        arguments: ["@doctrine.orm.entity_manager"]

    app.email.sending:
        class: AppBundle\Service\MaillerService
        arguments: ['@swiftmailer.mailer', '%mailer_sender_address%']

    app.getter_user_admin:
        class: AppBundle\Service\GetterUserAdmin
        arguments: ['@doctrine.orm.entity_manager']

    # Navigator Factory
    app.navigator.factory:
        class: AppBundle\Service\NavigatorFactory
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"

    # Navigator Service (Search/Filter/Pagination)
    app.navigator:
        class: AppBundle\Service\Navigator
        factory: "app.navigator.factory:get"