# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.sql.search_params_getter:
        class: AppBundle\Service\SqlWhereParamsSetter
        arguments: []

    app.email.sending:
        class: AppBundle\Service\MaillerService
        arguments: ['@service_container', '@swiftmailer.mailer']