# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.mailer_logger:
        class: AppBundle\Service\MailerLoggerService
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: mailer}
            - { name: 'swiftmailer.default.plugin' }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
