# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.mailer_logger:
        class: AppBundle\Service\MailerLoggerService
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: mailer}
            - { name: 'swiftmailer.default.plugin' }

    app.sql.search_params_getter:
        class: AppBundle\Service\SqlWhereParamsSetter
        arguments: []


    app.dictionary_verification:
        class: AppBundle\Service\DictionaryVerification
        arguments: ["@doctrine.orm.entity_manager"]
        arguments: []
