AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        roles:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: false
            column: is_active
        token:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        tokenLimitDate:
            type: datetime
            nullable: true
            column: token_limit_date
    lifecycleCallbacks: {  }
