AppBundle\Entity\UserTechnicalEvolution:
    type: entity
    table: user_technical_evolution
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        note:
            type: integer
            nullable: true
            options:
                unsigned: false
        comment:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
